"""empty message

Revision ID: 3b77f58a7de2
Revises: eb07665f58e5
Create Date: 2017-10-27 16:31:49.453590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b77f58a7de2'
down_revision = 'eb07665f58e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_and_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postid'], ['movies.postid'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('movies', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('uid', sa.INTEGER(), nullable=True))
    op.drop_table('user_and_movie')
    # ### end Alembic commands ###
