"""empty message

Revision ID: eb07665f58e5
Revises: 01de7e8e0506
Create Date: 2017-10-27 15:22:05.282582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb07665f58e5'
down_revision = '01de7e8e0506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('postid'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
